mining/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.utils.translation import ugettext as _
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings

admin.autodiscover()

#Main page
urlpatterns = patterns('repo.views',
    url(r'^$', TemplateView.as_view(template_name='repo/index.html'), {'title': _('Home')}, 'site_index'),
)

#Authentication
urlpatterns += patterns('',
    url(r'^accounts/', include('allauth.urls')),
)

#Admin system
urlpatterns += patterns('',
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

#Settings
urlpatterns += patterns('',
    url(r'^settings/', include('livesettings.urls')),
)

#Performance repository management
urlpatterns += patterns('',
    url(r'^repo/', include('repo.urls')),
)

urlpatterns += patterns('',
    url(r'^ajax/repo/', include('repo.urls_ajax')),
)

#Data analysis
urlpatterns += patterns('',
    url(r'^analysis/', include('analysis.urls')),
)

#Temporary hack for easier processing static files during development
urlpatterns += staticfiles_urlpatterns() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

repo/urls.py
from django.conf.urls import patterns, url
from django.utils.translation import ugettext as _
from django.views.generic import TemplateView
from repo.views import EnvironmentList, CounterList, EnvironmentDetail, CounterDetail, NodeDetail, NodeList, TestFileProcessCsvOpenTSDBDell, TestFileProcessXmlJmeter
from repo.views import TestFileProcessCsvOpenTSDB, EnvironmentDelete, NodeDelete, TestDelete, TestRunDelete, CounterDelete
from repo.views import TestDetail, TestList, TestRunDetail, TestRunList, RawCounterRecordList
from repo.views import RawCounterRecordDetail, CounterRecordDetail, CounterRecordList, TestFileList
from repo.views import TestFileDetail, TestFileDelete, TestFileFormatChooser, TestFileProcessCsv
from repo.views import RawCounterRecordDeleteAll, CounterRecordDeleteAll, TestFileProcessCsvJmeter

urlpatterns = patterns('',

    url(r'environments/(?P<environment>\d+)/tests/(?P<test>\d+)/testruns/(?P<testrun>\d+)/(?P<counter>\d+)/rawChart.png$',
        'repo.views.repo_chart_timeseries_raw', {}, 'repo_chart_timeseries_raw'),

    url(r'environments/(?P<environment>\d+)/tests/(?P<test>\d+)/testruns/(?P<testrun>\d+)/(?P<counter>\d+)/discreteChart.png$',
        'repo.views.repo_chart_timeseries_discrete', {}, 'repo_chart_timeseries_discrete'),

    url(r'environments/(?P<pk>\d+)/delete/$', EnvironmentDelete.as_view(), {}, 'repo_environment_delete'),

    url(r'environments/(?P<pk>\d+)/$', EnvironmentDetail.as_view(), {}, 'repo_environment_details'),

    url(r'environments/$', EnvironmentList.as_view(), {}, "repo_environments"),

    url(r'counters/(?P<pk>\d+)/delete/$', CounterDelete.as_view(), {}, "repo_counter_delete"),

    url(r'counters/(?P<pk>\d+)/$', CounterDetail.as_view(), {}, "repo_counter_details"),

    url(r'counters/$', CounterList.as_view(), {}, "repo_counters"),

    url(r'environments/(?P<environment>\d+)/nodes/(?P<pk>\d+)/delete/$', NodeDelete.as_view(), {}, "repo_node_delete"),

    url(r'environments/(?P<environment>\d+)/nodes/(?P<pk>\d+)/$', NodeDetail.as_view(), {}, "repo_node_details"),

    url(r'environments/(?P<environment>\d+)/nodes/$', NodeList.as_view(), {}, "repo_nodes"),

    url(r'environments/(?P<environment>\d+)/tests/(?P<pk>\d+)/delete/$', TestDelete.as_view(), {}, 'repo_test_delete'),

    url(r'environments/(?P<environment>\d+)/tests/(?P<pk>\d+)/$', TestDetail.as_view(), {}, "repo_test_details"),

    url(r'environments/(?P<environment>\d+)/tests/$', TestList.as_view(), {}, "repo_tests"),

    url(r'environments/(?P<environment>\d+)/tests/(?P<test>\d+)/testruns/(?P<pk>\d+)/delete/$',
        TestRunDelete.as_view(), {}, "repo_testrun_delete"),

    url(r'environments/(?P<environment>\d+)/tests/(?P<test>\d+)/testruns/(?P<pk>\d+)/$',
        TestRunDetail.as_view(), {}, "repo_testrun_details"),

    url(r'environments/(?P<environment>\d+)/tests/(?P<test>\d+)/testruns/$',
        TestRunList.as_view(), {}, "repo_testruns"),

    url(r'environments/(?P<environment>\d+)/tests/(?P<test>\d+)/testruns/(?P<testrun>\d+)/files/$',
        TestFileList.as_view(), {}, "repo_test_files"),

    url(r'environments/(?P<environment>\d+)/tests/(?P<test>\d+)/testruns/(?P<testrun>\d+)/files/(?P<pk>\d+)/$',
        TestFileDetail.as_view(), {}, "repo_test_file_details"),

    url(r'environments/(?P<environment>\d+)/tests/(?P<test>\d+)/testruns/(?P<testrun>\d+)/files/(?P<pk>\d+)/delete/$',
        TestFileDelete.as_view(), {}, "repo_test_file_delete"),

    url(r'environments/(?P<environment>\d+)/tests/(?P<test>\d+)/testruns/(?P<testrun>\d+)/files/(?P<pk>\d+)/process/$',
        TestFileFormatChooser.as_view(), {}, "repo_test_file_process"),

    url(r'environments/(?P<environment>\d+)/tests/(?P<test>\d+)/testruns/(?P<testrun>\d+)/files/(?P<pk>\d+)/process/error/$',
        TemplateView.as_view(template_name='repo/test_file_process_error.html'),
        {'title': _('An error has occurred')}, 'repo_test_file_process_error'),

    url(r'environments/(?P<environment>\d+)/tests/(?P<test>\d+)/testruns/(?P<testrun>\d+)/files/(?P<pk>\d+)/process/csv/jmeter/$',
        TestFileProcessCsvJmeter.as_view(), {}, "repo_test_file_process_csv_jmeter"),

    url(r'environments/(?P<environment>\d+)/tests/(?P<test>\d+)/testruns/(?P<testrun>\d+)/files/(?P<pk>\d+)/process/xml/jmeter/$',
        TestFileProcessXmlJmeter.as_view(), {}, "repo_test_file_process_xml_jmeter"),

    url(r'environments/(?P<environment>\d+)/tests/(?P<test>\d+)/testruns/(?P<testrun>\d+)/files/(?P<pk>\d+)/process/csv/opentsdb_dell/$',
        TestFileProcessCsvOpenTSDBDell.as_view(), {}, "repo_test_file_process_csv_opentsdbdell"),

    url(r'environments/(?P<environment>\d+)/tests/(?P<test>\d+)/testruns/(?P<testrun>\d+)/files/(?P<pk>\d+)/process/csv/opentsdb/$',
        TestFileProcessCsvOpenTSDB.as_view(), {}, "repo_test_file_process_csv_opentsdb"),

    url(r'environments/(?P<environment>\d+)/tests/(?P<test>\d+)/testruns/(?P<testrun>\d+)/files/(?P<pk>\d+)/process/csv/(?P<format>\w+)/$',
        TestFileProcessCsv.as_view(), {}, "repo_test_file_process_csv_generic"),

    url(r'environments/(?P<environment>\d+)/tests/(?P<test>\d+)/testruns/(?P<testrun>\d+)/rawcounterrecords/$',
        RawCounterRecordList.as_view(), {}, "repo_raw_counter_records"),

    url(r'environments/(?P<environment>\d+)/tests/(?P<test>\d+)/testruns/(?P<testrun>\d+)/rawcounterrecords/delete/$',
        RawCounterRecordDeleteAll.as_view(), {}, "repo_raw_counter_records_delete"),

    url(r'environments/(?P<environment>\d+)/tests/(?P<test>\d+)/testruns/(?P<testrun>\d+)/rawcounterrecords/(?P<pk>\d+)/$',
        RawCounterRecordDetail.as_view(), {}, "repo_raw_counter_records_details"),

    url(r'environments/(?P<environment>\d+)/tests/(?P<test>\d+)/testruns/(?P<testrun>\d+)/consolidatedcounterrecords/$',
        CounterRecordList.as_view(), {}, "repo_consolidated_counter_records"),

    url(r'environments/(?P<environment>\d+)/tests/(?P<test>\d+)/testruns/(?P<testrun>\d+)/consolidatedcounterrecords/delete/$',
        CounterRecordDeleteAll.as_view(), {}, "repo_consolidated_counter_records_delete"),

    url(r'environments/(?P<environment>\d+)/tests/(?P<test>\d+)/testruns/(?P<testrun>\d+)/consolidatedcounterrecords/(?P<pk>\d+)/$',
        CounterRecordDetail.as_view(), {}, "repo_consolidated_counter_records_details"),

    url(r'$', TemplateView.as_view(template_name='repo/repo.html'),
        {'title': _('Performance testing repository')} ,"repo_index"),
)

repo/models.py
from cache_utils.decorators import cached
from livesettings import config_value
import os
from django.core.urlresolvers import reverse
from django.db import models

from django.utils.translation import ugettext as _
from pytz import timezone
from mining import settings
from repo import ConverterParametersCsv, ConverterParametersXmlJmeter
from repo import REPO_CLASSIFIER
from precise_datetime import PreciseDateTimeField
#noinspection PyUnresolvedReferences
import config


class Environment(models.Model):
    name = models.CharField(max_length=100)

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('repo_env_details', args=[str(self.id)])

    def get_test_ids(self):
        return Test.objects.filter(environment__id=self.id).values_list('id', flat=True)

    def test_files(self):
        result = []
        tests = self.test_set.all()
        for test in tests:
            result += test.test_files()
        return result


class Counter(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    is_node_related = models.BooleanField(default=False,
        help_text=_('True for node-related counters, i.e. CPU, False for environment-related, i.e. response time'))

    def __unicode__(self):
        return self.name


class Node(models.Model):
    name = models.CharField(max_length=100)
    role = models.CharField(max_length=200, blank=True)
    environment = models.ForeignKey(Environment)

    def __unicode__(self):
        return "%s (%s)" % (self.name, self.environment.name)

    def get_absolute_url(self):
        return reverse('repo_node_details', args=[str(self.environment.id), str(self.id)])


class CounterRecordClass(models.Model):
    label = models.CharField(max_length=200, db_index=True)
    counter = models.ForeignKey(Counter)

    def __unicode__(self):
        return '%(label)s - %(counter)s' % {'label': self.label, 'counter': self.counter}

    class Meta():
        unique_together = (('label', 'counter'),)
        ordering = ('label', 'counter')


class Test(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    environment = models.ForeignKey(Environment)
    sampling_period = models.IntegerField(
        help_text=_('Unified sampling period for all test runs and counters, in seconds'))
    disabled_counters = models.ManyToManyField(CounterRecordClass, blank=True)

    def __unicode__(self):
        return '%(test)s at %(environment)s' \
               % {'test': self.name, 'environment': self.environment.name}

    def get_absolute_url(self):
        return reverse('repo_test_details', args=[str(self.environment.id), str(self.id)])

    def test_files(self):
        result = []
        testruns = self.testrun_set.all()
        for run in testruns:
            result += run.test_files()
        return result

    def get_baseline_testrun_ids(self, limit=False):
        """
        Return ids of baseline test runs for the test ordered in descending time order.
        @param boolean limit: limit number of runs by REPO_MAX_TEST_RUNS_FOR_BASELINE.
        @return [int]: list of ids
        """
        return [t.id for t in self.get_baseline_testruns(limit)]

    def get_baseline_testruns(self, limit=False):
        """
        Return list of baseline test runs for the test ordered in descending time order.
        @param boolean limit: limit number of runs by REPO_MAX_TEST_RUNS_FOR_BASELINE.
        @return [TestRun]: list of test runs
        """
        testruns = self.testrun_set.filter(is_baseline=True).order_by('time_end').reverse()
        max_baseline_runs = config_value('repo_model', 'MAX_TEST_RUNS_FOR_BASELINE')
        if limit and max_baseline_runs > 0:
            return testruns[:max_baseline_runs]
        else:
            return testruns

    def get_target_testruns(self):
        """
        Return list of target test runs for the test ordered in descending time order.
        @return [TestRun]: list of test runs
        """
        return self.testrun_set.filter(is_baseline=False).order_by('time_end').reverse()

    def get_raw_baseline_counter_values_for_class_id(self, clazz, is_sorted=True):
        baseline_ids = self.get_baseline_testrun_ids()
        return RawCounterRecord.get_values_for_class(baseline_ids, clazz, is_sorted)

    def get_consolidated_baseline_counter_values_for_class_id(self, clazz, is_sorted=True):
        baseline_ids = self.get_baseline_testrun_ids()
        return ConsolidatedCounterRecord.get_values_for_class(baseline_ids, clazz, is_sorted)

    def get_baseline_transactions(self):
        result = []
        baseline_runs = self.testrun_set.filter(is_baseline=True).order_by('time_end').reverse()
        for run in baseline_runs:
            transactions = run.get_transactions()
            result += transactions
        return result


class TestRun(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    test = models.ForeignKey(Test)
    time_start = models.DateTimeField()
    time_end = models.DateTimeField()
    is_baseline = models.BooleanField(default=False)

    def __unicode__(self):
        return '%(testrun)s run (%(test)s)' \
               % {'testrun': self.name, 'test': self.test.name}

    def get_absolute_url(self):
        return reverse('repo_testrun_details', args=[str(self.test.environment.id),
                                                     str(self.test.id),
                                                     str(self.id)])

    def remove_raw_counter_records(self):
        RawCounterRecord.objects.filter(testrun__id=self.id).delete()

    def remove_consolidated_counter_records(self):
        ConsolidatedCounterRecord.objects.filter(testrun__id=self.id).delete()

    def get_formatted_time(self, dt):
        return dt.astimezone(timezone(settings.TIME_ZONE)).strftime(config_value('repo_model', 'DATE_TIME_FORMAT_MIN'))

    def formatted_start(self):
        return self.get_formatted_time(self.time_start)

    def formatted_end(self):
        return self.get_formatted_time(self.time_end)

    @cached(settings.CACHE_TIMEOUT)
    def get_transactions(self):
        """
        Return list of transactions, where each transaction is a list
        of consolidated performance counters with same offset.
        Array index is equal to the offset
        Records for disabled counters are not returned
        @return [[ConsolidatedCounterRecord]]
        """
        disabled_counter_classes = CounterRecordClass.objects. \
            filter(test__id__exact=self.test.id).values_list('id', flat=True)

        records = ConsolidatedCounterRecord.objects \
            .select_related('clazz__label', 'clazz__counter__name') \
            .filter(testrun__id=self.id) \
            .exclude(clazz__id__in=disabled_counter_classes) \
            .order_by('offset', 'clazz__label', 'clazz__counter__name')

        classifier = REPO_CLASSIFIER(testrun=self)
        transactions = []
        current_transaction = []
        current_offset = 0

        for record in records:
            if record.offset != current_offset:
                transactions.append(current_transaction)
                current_transaction = []
                current_offset += 1
            current_transaction.append(record)
        transactions.append(current_transaction)
        [classifier.classify(t) for t in transactions]

        return transactions

    def get_valid_classes(self):
        """
        @return [int] ids: list of raw counter record class ids that are used as identifiers
        for the associated counter records
        """
        return list(RawCounterRecord.objects.
            filter(testrun_id=self.id).order_by().values_list('clazz_id', flat=True).distinct())

    def test_files(self):
        return list(self.testfile_set.all())


class TestFile(models.Model):
    testrun = models.ForeignKey(TestRun)
    file = models.FileField(upload_to='test_files')
    uploaded_at = models.DateTimeField()
    original_name = models.CharField(max_length=254)

    def __unicode__(self):
        result = os.path.join(self.testrun.name, self.original_name)
        if self.uploaded_at:
            result += ' : ' + self.uploaded_at.strftime(config_value('repo_model', 'DATE_TIME_FORMAT_MIN'))
        return result

    def get_absolute_url(self):
        return reverse('repo_testfile_details', args=[str(self.testrun.test.environment.id),
                                                      str(self.testrun.test.id),
                                                      str(self.testrun.id),
                                                      str(self.id)])

    def get_parameters_for_jmeter_csv(self):
        parameters = ConverterParametersCsv(self)
        parameters.testrun_id = self.testrun.id
        parameters.testrun_start = self.testrun.time_start
        parameters.testrun_end = self.testrun.time_end
        parameters.node_related = False
        parameters.timestamp_column = 'timeStamp'
        parameters.label_column = 'label'
        latency_counter_id = Counter.objects.get(name='Latency').id
        parameters.counters.append((latency_counter_id, 'Latency'))
        return parameters

    def get_parameters_for_jmeter_xml(self):
        parameters = ConverterParametersXmlJmeter(self)
        parameters.testrun_id = self.testrun_id
        parameters.testrun_start = self.testrun.time_start
        parameters.testrun_end = self.testrun.time_end
        parameters.node_related = False
        latency_counter_id = Counter.objects.get(name='Latency').id
        parameters.counters.append((latency_counter_id, '@lt'))
        return parameters

    def get_parameters_for_opentsdb(self):
        parameters = ConverterParametersCsv(self)
        parameters.testrun_id = self.testrun.id
        parameters.testrun_start = self.testrun.time_start

repo/templates/repo/base.html
{% extends 'base.html' %}

repo/templates/repo/counter_detail.html
{% extends "repo/base.html" %}
{% load i18n %}

{% block content %}
        {% trans 'Name: ' %}{{ counter.name }} <br/>
        {% trans 'Node-related: ' %}{{ counter.is_node_related }}
{% endblock %}

repo/templates/repo/environment_detail.html
{% extends "repo/base.html" %}
{% load i18n %}

{% block content %}
    <h4>{% trans "Tests" %}</h4>
    {% if environment.test_set.all %}
        <table class="table" style="width:auto">
            <tbody>
            {% for test in environment.test_set.all %}
                <div id="modaltest{{ test.id }}" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="modal{{ test.id }}Label" aria-hidden="true">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                        <h4 id="label{{ test.id }}">{% trans 'Test removal' %}</h4>
                    </div>
                    <div class="modal-body">
                        <p>{% blocktrans with name=test.name %}Are you sure you want to remove test <i>{{ name }}</i>?{% endblocktrans %}</p>
                    </div>
                    <div class="modal-footer">
                        <form method="post" action="{% url 'repo_test_delete' environment.id test.id %}">
                            {% csrf_token %}
                            <button class="btn" data-dismiss="modal" aria-hidden="true">{% trans 'Cancel' %}</button>
                            <button class="btn btn-danger" type="submit"><i class="icon-trash icon-white"></i>{% trans ' Remove' %}</button>
                        </form>
                    </div>
                </div>

                <tr>
                    <td><a href="{% url 'repo_test_details' environment.id test.id %}">{{ test.name }}</a></td>
                    <td><a href="{% url 'admin:repo_test_change' test.id %}" target='_blank'><i class="icon-edit"></i></a></td>
                    <td><a href="#modaltest{{ test.id }}" data-toggle="modal"><i class="icon-remove"></i></a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>{% trans "No tests were created for this environment." %}</p>
    {% endif %}

    <a href="{% url 'admin:repo_test_add' %}" target='_blank'>
        <button type='button' class='btn btn-small btn-primary'>{% trans 'Add test' %}</button>
    </a>

    <br/><br/>

    <h4>{% trans "Nodes" %}</h4>
    {% if environment.node_set.all %}
        <table class="table" style="width:auto">
            <tbody>
                {% for node in environment.node_set.all %}
                <div id="modalnode{{ node.id }}" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="modal{{ node.id }}Label" aria-hidden="true">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                        <h4 id="label{{ node.id }}">{% trans 'Node removal' %}</h4>
                    </div>
                    <div class="modal-body">
                        <p>{% blocktrans with name=node.name %}Are you sure you want to remove node <i>{{ name }}</i>?{% endblocktrans %}</p>
                    </div>
                    <div class="modal-footer">
                        <form method="post" action="{% url 'repo_node_delete' environment.id node.id %}">
                            {% csrf_token %}
                            <button class="btn" data-dismiss="modal" aria-hidden="true">{% trans 'Cancel' %}</button>
                            <button class="btn btn-danger" type="submit"><i class="icon-trash icon-white"></i>{% trans ' Remove' %}</button>
                        </form>
                    </div>
                </div>

                <tr>
                    <td><a href="{% url 'repo_node_details' environment.id node.id %}">{{ node.name }}</a></td>
                    <td><a href="{% url 'admin:repo_node_change' node.id %}" target='_blank'><i class="icon-edit"></i></a></td>
                    <td><a href="#modalnode{{ node.id }}" data-toggle="modal"><i class="icon-remove"></i></a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>{% trans "No nodes are associated with this environment." %}</p>
    {% endif %}

    <a href="{% url 'admin:repo_node_add' %}" target='_blank'>
        <button type='button' class='btn btn-small btn-primary'>{% trans 'Add node' %}</button>
    </a>
{% endblock %}

repo/templates/repo/environment_list.html
{% extends "repo/base.html" %}
{% load i18n %}
{% load admin_urls %}

{% block content %}
    <table class="table" style="width:auto">
        <tbody>
            {% for environment in object_list %}
            <div id="modal{{ environment.id }}" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="modal{{ file.id }}Label" aria-hidden="true">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 id="label{{ environment.id }}">{% trans 'Environment removal' %}</h4>
                </div>
                <div class="modal-body">
                    <p>{% blocktrans with name=environment.name %}Are you sure you want to remove environment <i>{{ name }}</i>?{% endblocktrans %}</p>
                </div>
                <div class="modal-footer">
                    <form method="post" action="{% url 'repo_environment_delete' environment.id %}">
                        {% csrf_token %}
                        <button class="btn" data-dismiss="modal" aria-hidden="true">{% trans 'Cancel' %}</button>
                        <button class="btn btn-danger" type="submit"><i class="icon-trash icon-white"></i>{% trans ' Remove' %}</button>
                    </form>
                </div>
            </div>

            <tr>
                <td><a href="{% url 'repo_environment_details' environment.id %}">{{ environment.name }}</a></td>
                <td><a href="{% url 'admin:repo_environment_change' environment.id %}" target='_blank'><i class="icon-edit"></i></a></td>
                <td><a href="#modal{{ environment.id }}" data-toggle="modal"><i class="icon-remove"></i></a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <a href="{% url 'admin:repo_environment_add' %}" target='_blank'>
        <button type='button' class='btn btn-small btn-primary'>{% trans 'Add environment' %}</button>
    </a>
{% endblock %}

repo/templates/repo/index.html
{% extends 'repo/base.html' %}
{% load i18n %}
{% load static %}

{% block head_title %}{% trans 'TomTom performance repository' %}{% endblock head_title %}
{% block page_title %}
    <div class="row">
        <div class="span6 offset3">
            <h2 style="text-align:center">TomTom performance repository</h2>
        </div>
    </div>
{% endblock page_title %}

{% block content %}
    <div class="row">
        <div class="span6 offset3"><br/><br/>
            <img src="{% static 'images/home.png' %}"/>
        </div>
    </div>

{% endblock content %}

repo/templates/repo/node_detail.html
{% extends "repo/base.html" %}
{% load i18n %}

{% block content %}
        {% blocktrans with role=node.role %} Role: {{ role }}{% endblocktrans%}<br/>
{% endblock %}

repo/templates/repo/node_list.html
{% extends "repo/base.html" %}
{% load i18n %}

{% block content %}
    <ul class="unstyled">
        {% if node_list %}
            {% for node in node_list %}
                <li><a href="{% url 'repo_node_details' node.environment.id node.id %}">{{ node.name }}</a></li>
            {% endfor %}
        {% else %}
            {% trans 'No nodes are defined for this environment.' %}
        {% endif %}
    </ul>
{% endblock %}

repo/templates/repo/pager.html
{% load i18n %}

{% if is_paginated %}
    <div class="pagination">
        <span class="page-links">
            {% if page_obj.has_previous %}
                <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">{% trans 'previous' %}</a>
            {% endif %}
            <span class="page-current">
                {% blocktrans with current=page_obj.number total=page_obj.paginator.num_pages %}
                    page {{ current }} of {{ total }}
                {% endblocktrans %}
            </span>
            {% if page_obj.has_next %}
                <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">{% trans 'next' %}</a>
            {% endif %}
        </span>
    </div>
{% endif %}

repo/templates/repo/rawcounterrecord_detail.html
{% extends "repo/base.html" %}
{% load i18n %}

{% block content %}
        <h4>{% trans 'Metadata' %}</h4>
        {% include 'repo/testrun_metadata.html' with instance=rawcounterrecord %}

        <br/>

        <h4>{% trans 'Data' %}</h4>
        {% trans 'Name: ' %}{{ rawcounterrecord.clazz.name }}<br/>
        {% trans 'Timestamp: ' %}{{ rawcounterrecord.get_formatted_datetime }}<br/>
        {% trans 'Counter: ' %}<a href="{% url 'repo_counter_details' rawcounterrecord.clazz.counter.id %}">{{ rawcounterrecord.clazz.counter.name }}</a><br/>
        {% trans 'Value: ' %}{{ rawcounterrecord.value }}
{% endblock %}

repo/templates/repo/rawcounterrecord_list.html
{% extends "repo/base.html" %}
{% load i18n %}

{% block content %}
    {% if rawcounterrecord_list %}
        {% include 'repo/pager.html' %}
        <ul class="unstyled">
            {% for raw_counter_record in rawcounterrecord_list %}
                {# Call via request for performance matters  #}
                <li><a href="{{ request.path }}{{raw_counter_record.id}}/">
                    {{ raw_counter_record.clazz.label }} : {{ raw_counter_record.clazz.counter.name }} : {{ raw_counter_record.get_formatted_datetime }}</a></li>
            {% endfor %}
        </ul>
        {% include 'repo/pager.html' %}
    {% else %}
        {% trans 'No raw counter records exist for this test run.' %}
    {% endif %}
{% endblock %}

{% block sidebar %}
        <ul class="unstyled">
            <li><a href="{% url 'repo_testrun_details' testrun.test.environment.id testrun.test.id testrun.id %}">
                {% trans 'Back to test run details' %}</a></li>
        </ul>
{% endblock sidebar %}

repo/templates/repo/repo.html
{% extends 'repo/base.html' %}
{% load i18n %}

{% block content %}
    <ul class="unstyled">
        <li><a href="{% url 'repo_environments' %}">{% trans 'Environments' %}</a></li>
        <li><a href="{% url 'repo_counters' %}">{% trans 'Counters' %}</a></li>
    </ul>
{% endblock content %}